# Docker for Java Developers

This folder contains instructions to setup an Instructor environment.

Instructor needs:

. A docker registry server
. A Boot2docker served by a local HTTP Server
. A Nexus Proxy

## Install Boot2docker

## Install Docker-machine

## Create Machine

[source, text]
----
docker-machine create --driver virtualbox mymachine
----

## Add extra args to docker host to allow insecure registry for external access via http:

[source, text]
----
docker-machine ssh

$ # add EXTRA_ARGS="--insecure-registry <YOUR INSECURE HOST>" 
$ # to /var/lib/boot2docker/profile
$ sudo /etc/init.d/docker restart
----

Check machine IP
[source, text]
----
docker-machine ip
----

Further on refered to as <HOST_IP>

## Run local-registry

Instructors should run a local registry to make all images locally available to attendees

[source, text]
----
docker run -p 5000:5000 registry:2.0
----


## Build Boot2docker-http image

[source, text]
----
docker build -t boot2docker-httpd:latest boot2docker-http/.
----

Check Image ID  and use subsequently, refered to as <IMAGE_ID>

## Tag Image for Local registry

docker tag <IMAGE_ID> <HOST_IP>:5000/boot2docker-http:latest

## Push Boot2docker-http image to local registry

The boot2docker-http server is pushed to local registry.

[source, text]
----
docker push <HOST_IP>:5000/boot2docker-httpd:latest
----

Check if image upload was a success
[source, text]
----
http://<HOST_IP>:5000/v2/boot2docker-http/tags/list
----


## Run boot2docker http server

Run the boot2docker Apache server for attendees to download iso image.

[source, text]
----
docker run -d --name="boot2docker-httpd" -p 1500:80 boot2docker-httpd
docker run -p 1500:80 <HOST_IP>:5000/boot2docker-http
----

## Run Nexus On the instructor machine

Default credentials are: admin / admin123

[source, text]
----
mkdir /some/dir/nexus-data && chown -R 200 /some/dir/nexus-data

docker run -d -p 8081:8081 --name nexus -v /some/dir/nexus-data:/sonatype-work sonatype/nexus:oss

docker run -d -p 8081:8081 --name nexus sonatype/nexus:oss -v /some/dir/nexus-data:/sonatype-work sonatype/nexus
----

Test if nexus is running:

[source, text]
----
 curl http://localhost:8081/service/local/status
----

