# Docker for Java Developers

This folder contains instructions to setup an Instructor environment.

IMPORTANT: Make sure to run these instructions prior to the lab already. Executing them might take up to 30 minutes.

Instructor needs:

. A docker registry server
. A Boot2docker served by a local HTTP Server
. A Nexus Proxy

## Prerequisites

. Have https://www.virtualbox.org/[Oracle Virtualbox] installed and the install folder added to your PATH environment variable.
. Have the https://github.com/arun-gupta/docker-java/ git repository checked out.
. Have https://msysgit.github.io/ installed on windows

## Install Docker Client

[source, text]
----
# Linux / MacOS
curl -L  https://get.docker.com/builds/Darwin/x86_64/docker-latest > /usr/local/bin/docker

#Windows 
Download: 
https://get.docker.com/builds/Windows/x86_64/docker-latest.exe
https://get.docker.com/builds/Windows/i386/docker-latest.exe
And save to c:/Users/<username>/docker/docker.exe
----

## Install Docker compose

[source, text]
----
# Linux / MacOS
curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
----

## Install Docker-machine

Install the Docker machine client for your environment: https://github.com/docker/machine/releases/[latest releases]

[source, text]
----
# Linux / MacOS
curl -L  https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_darwin-amd64 > /usr/local/bin/docker-machine

# Windows
Download:
https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_windows-amd64.exe
And save to c:/Users/<username>/docker/docker-machine.exe
----

For Windows, make sure to add c:/Users/<username>/docker to your %PATH% variable.

## Create Machine

[source, text]
----
docker-machine create --driver virtualbox mymachine
----

## Expose the Virtual Box ports to other computer in the LAN

VirtualBox will run docker container inside the newly create host called 'mymachine'. We need now to expose the ports used in this lab to the world.

[source, text]
----
#Open Registry Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port5000,tcp,,5000,,5000";
#Open Nexus Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8081,tcp,,8081,,8081";
#Open HTTP Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8082,tcp,,8082,,8082";
#Open gitlab ports
VBoxManage controlvm "mymachine" natpf1 "tcp-port10022,tcp,,10022,,10022";
VBoxManage controlvm "mymachine" natpf1 "tcp-port10080,tcp,,10080,,10080";
----


Check machine IP
[source, text]
----
docker-machine ip
----

Further on refered to as <HOST_IP>

## Add extra args to docker host to allow insecure registry for external access via http:
You can either insert your <HOST_IP> or the complete subnet e.g. 192.168.99.100 maps to 192.168.99.0/24

[source, text]
----
docker-machine ssh

$ # add EXTRA_ARGS="--insecure-registry <YOUR INSECURE HOST>" 
$ # to /var/lib/boot2docker/profile
$ sudo /etc/init.d/docker restart
----

## Create a container with Nexus dependencies

[source, text]
----
docker run --name="nexusdata" -v $(pwd):/backup sonatype/nexus:oss bash -c "tar xvf  /backup/nexusbackup.tar -C /"
----

## Start the Instructor environment

_Note: This command should take some time to execute_

[source, text]
----
docker-compose up -d
----

Test if the servers are running:

Access the docker registry [http://localhost:5000/v2/].

Access the nexus console [http://localhost:8081/content/groups/public/].

Access the webserver [http://localhost:8082/].

Access the gitlab server [http://localhost:10080/].


## Populate Gitlab with Ticket-monster sources

Execute:

[source,text]
----
docker exec instructor_gitlab_1 bash -c "cd /home/git/data/repositories/root; git clone --bare https://github.com/jboss-developer/ticket-monster.git; chown git:git -R /home/git/data/repositories; cd /home/git/gitlab; sudo -u git -H bundle exec rake -v gitlab:import:repos RAILS_ENV=production"
----

## Build TicketMonster from the sources

1. Clone TicketMonster from the existing gitlab container

  git clone -b WFLY8.1 http://root:dockeradmin@localhost:10080/root/ticket-monster.git

2. Build TicketMonster

  mvn -s settings.xml -f ticket-monster/demo/pom.xml package

3. Copy TicketMonster war to the docker ticketmonster-pgsql-widlfly image folder

  cp ticket-monster/demo/target/ticket-monster.war dockerfiles/ticketmonster-pgsql-wildfly/

## Build ticketmonster-pgsql-widlfly image

[source, text]
----
docker build -t "instructor/ticketmonster-pgsql-wildfly" dockerfiles/ticketmonster-pgsql-wildfly/
----

## Put the ticketmonster-pgsql-wildfly and postgres images on the local registry

[source, text]
----
# Ticket-monster+PGSQ+WildFly
docker tag instructor/ticketmonster-pgsql-wildfly localhost:5000/ticketmonster-pgsql-wildfly
docker push localhost:5000/ticketmonster-pgsql-wildfly

# Postgres
docker pull postgres
docker tag postgres localhost:5000/postgres
docker push localhost:5000/postgres
----

## More information

If you need some extra information like:

- Uptating the attendees instructions served by the instructor httpd server
- Backing up Nexus data container to a file

Please, check the link:extra.adoc[extra instructions].