# Docker for Java Developers

This folder contains instructions to setup an Instructor environment.

Instructor needs:

. A docker registry server
. A Boot2docker served by a local HTTP Server
. A Nexus Proxy

## Install Boot2docker

## Install Docker-machine

## Create Machine

[source, text]
----
docker-machine create --driver virtualbox --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.5.0/boot2docker.iso mymachine
----

## Expose the Virtual Box ports to other computer in the LAN

VirtualBox will run docker container inside the newly create host called 'mymachine'. We need now to expose the ports used in this lab to the world.

[source, text]
----
#Open Registry Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port5000,tcp,,5000,,5000";
#Open Nexus Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8081,tcp,,8081,,8081";
#Open HTTP Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8082,tcp,,8082,,8082";
----
## Add extra args to docker host to allow insecure registry for external access via http:

[source, text]
----
docker-machine ssh

$ # add EXTRA_ARGS="--insecure-registry <YOUR INSECURE HOST>" 
$ # to /var/lib/boot2docker/profile
$ sudo /etc/init.d/docker restart
----

Check machine IP
[source, text]
----
docker-machine ip
----

Further on refered to as <HOST_IP>

## Run local-registry

Instructors should run a local registry to make all images locally available to attendees

[source, text]
----
docker run -dp --name="docker-registry" 5000:5000 registry:2.0
----


## Build the Lab HTTPD Server image

[source, text]
----
docker build -t lab-httpd-server:latest lab-httpd-server/.
----

Check Image ID  and use subsequently, refered to as <IMAGE_ID>

## Tag Image for Local registry TODO - Remove this section

docker tag <IMAGE_ID> <HOST_IP>:5000/lab-httpd-server:latest

## Push Boot2docker-http image to local registry

The boot2docker-http server is pushed to local registry.

[source, text]
----
docker push <HOST_IP>:5000/lab-httpd-server:latest
----

Check if image upload was a success
[source, text]
----
http://<HOST_IP>:5000/v2/lab-httpd-server/tags/list
----


## Run Http server with downloadables

Run the Apache HTTPD server for attendees to download boot2docker iso image and Virtuabox binaries.

[source, text]
----
docker run -d --name="lab-httpd-server" -p 8082:80 lab-httpd-server
docker run -p 8082:80 <HOST_IP>:5000/lab-httpd-server - TODO remove this section
----

## Run Nexus On the instructor machine

Default credentials are: admin / admin123

[source, text]
----
docker run -d -p 8081:8081 --name nexus sonatype/nexus:oss
----

TODO: 
Storage directory:
mkdir /some/dir/nexus-data && chown -R 200 /some/dir/nexus-data
docker run -d -p 8081:8081 --name nexus sonatype/nexus:oss -v /some/dir/nexus-data:/sonatype-work sonatype/nexus


Test if nexus is running:

[source, text]
----
 curl http://localhost:8081/service/local/status
----

