= Docker for Java Developers - Instructor Setup
:toc:
:toc-placement!:

This folder contains instructions to setup an Instructor environment.

toc::[]

IMPORTANT: Make sure to run these instructions prior to the lab already. Executing them might take up to 60 minutes.

Instructor needs:

. A docker registry server
. A Boot2docker served by a local HTTP Server
. A Nexus Proxy

## Prerequisites

. Have https://www.virtualbox.org/[Oracle Virtualbox] installed and the install folder added to your PATH environment variable.
. Have the https://github.com/arun-gupta/docker-java/ git repository checked out.
. Have https://msysgit.github.io/ installed on Windows

## Install Docker Client
The docker client is the minimum requirement to have. Download and install by just copying and renaming it accordingly.

[source, text]
----
# Linux / MacOS
curl -L  https://get.docker.com/builds/Darwin/x86_64/docker-latest > /usr/local/bin/docker

#Windows
Download:
https://get.docker.com/builds/Windows/x86_64/docker-latest.exe
https://get.docker.com/builds/Windows/i386/docker-latest.exe
And save to c:\Users\<username>\docker\docker.exe
----

## Install Docker compose
We use compose to make the setup for the instructor as easy as possible. The link:https://github.com/arun-gupta/docker-java/blob/master/instructor/docker-compose.yml[docker-compose.yml] contains all the instructions for the tool to setup and start the infrastructure.
Learn more about it by visiting the link:https://docs.docker.com/compose/[Docker Compose Website].


[source, text]
----
# Linux / MacOS
curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
----

## Install Docker-machine
Install the Docker machine client for your environment: https://github.com/docker/machine/releases/[latest releases]

[source, text]
----
# Linux / MacOS
curl -L  https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_darwin-amd64 > /usr/local/bin/docker-machine

# Windows
Download:
https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_windows-amd64.exe
And save to c:\Users\<username>\docker\docker-machine.exe
----

For Windows, make sure to add c:\Users\<username>\docker to your %PATH% variable. This was already done for Linux / MacOs when you downloaded docker-machine to /usr/local/bin/docker-machine .

## Create Machine
This creates your instructor host which will run the complete infrastructure.
[source, text]
----
docker-machine create --driver=virtualbox --virtualbox-memory=4096 mymachine
----

## Expose the Virtual Box ports to other computer in the LAN

VirtualBox will run docker container inside the newly create host called 'mymachine'. We need now to expose the ports used in this lab to the world.

[source, text]
----
#Open Registry Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port5000,tcp,,5000,,5000";
#Open Nexus Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8081,tcp,,8081,,8081";
#Open HTTP Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8082,tcp,,8082,,8082";
#Open gitlab ports
VBoxManage controlvm "mymachine" natpf1 "tcp-port10022,tcp,,10022,,10022";
VBoxManage controlvm "mymachine" natpf1 "tcp-port10080,tcp,,10080,,10080";
----


Check machine IP
[source, text]
----
docker-machine ip
----

Further on refered to as <HOST_IP>

## Add extra args to docker host to allow insecure registry for external access via http:
You can either insert your <HOST_IP> or the complete subnet e.g. 192.168.99.100 maps to 192.168.99.0/24

[source, text]
----
docker-machine ssh

$ # add EXTRA_ARGS="--insecure-registry <YOUR INSECURE HOST>"
$ # to /var/lib/boot2docker/profile
$ sudo /etc/init.d/docker restart
----

## Create a container with Nexus dependencies
We want to provide the option to run this lab without any internet access at all. So, the instructor machine will contain everything that the attendees will need to run this lab.
[source, text]
----
docker run --name="nexusdata" -v $(pwd):/backup sonatype/nexus:oss bash -c "tar xvf  /backup/nexusbackup.tar -C /"
----

## Start the Instructor environment
Download link:https://www.jboss.org/download-manager/content/origin/files/sha256/0e/0e3e78a641196d21742730f23a6e1c9aa04e0596c16349e74dbd4ea2d1109d40/jboss-devstudio-8.1.0.GA-installer-standalone.jar[JBDS 8.10.GA - 567 MB] and place it inside *dockerfiles/lab-httpd-server/downloads* folder.

Use the following compose command to startup the complete environment at once.
_Note: This command should take some time to execute_

[source, text]
----
docker-compose up -d
----

Test if the servers are running:

Access the docker registry [http://localhost:5000/v2/].

Access the nexus console [http://localhost:8081/content/groups/public/].

Access the webserver [http://localhost:8082/].

Access the gitlab server [http://localhost:10080/].


## Populate Gitlab with Ticket-monster sources
In order to allow a complete offline experience, we also host our own git repository for the demo application on the instructor machine.

_Note: Gitlab must have completed his startup. It usually takes 3 minutes to do so._
Execute:

[source,text]
----
docker exec instructor_gitlab_1 bash -c "cd /home/git/data/repositories/root; git clone --bare https://github.com/rafabene/ticket-monster.git; chown git:git -R /home/git/data/repositories; cd /home/git/gitlab; sudo -u git -H bundle exec rake -v gitlab:import:repos RAILS_ENV=production"
----

## Build TicketMonster from the sources

1. Clone TicketMonster from the existing gitlab container

  git clone -b WildFly-docker-test http://root:dockeradmin@localhost:10080/root/ticket-monster.git

2. Build TicketMonster

  mvn -s settings.xml -f ticket-monster/demo/pom.xml -Ppostgresql clean package

3. Copy TicketMonster war to the docker ticketmonster-pgsql-widlfly image folder

  cp ticket-monster/demo/target/ticket-monster.war dockerfiles/ticketmonster-pgsql-wildfly/

## Build managed-widlfly and ticketmonster-pgsql-widlfly images

[source, text]
----
docker build -t "instructor/wildfly-management" dockerfiles/wildfly-management/
docker build -t "instructor/ticketmonster-pgsql-wildfly" dockerfiles/ticketmonster-pgsql-wildfly/
----

## Put the managed-wildfly, ticketmonster-pgsql-wildfly, postgres and modcluster images on the local registry

[source, text]
----
# Wildfly
docker pull jboss/wildfly
docker tag jboss/wildfly localhost:5000/wildfly
docker push localhost:5000/wildfly

# Managed WildFly
docker tag instructor/wildfly-management localhost:5000/wildfly-management
docker push localhost:5000/wildfly-management

# Ticket-monster+PGSQ+WildFly
docker tag instructor/ticketmonster-pgsql-wildfly localhost:5000/ticketmonster-pgsql-wildfly
docker push localhost:5000/ticketmonster-pgsql-wildfly

# Postgres
docker pull postgres
docker tag postgres localhost:5000/postgres
docker push localhost:5000/postgres

# Modcluster
docker pull goldmann/mod_cluster
docker tag goldmann/mod_cluster localhost:5000/mod_cluster
docker push localhost:5000/mod_cluster
----

## More information

If you need some extra information like:

- Uptating the attendees instructions served by the instructor httpd server
- Backing up Nexus data container to a file

Please, check the link:extra.adoc[extra instructions].
