# Docker for Java Developers

This folder contains instructions to setup an Instructor environment.

IMPORTANT: Make sure to run these instructions prior to the lab already. Executing them might take up to 30 minutes.

Instructor needs:

. A docker registry server
. A Boot2docker served by a local HTTP Server
. A Nexus Proxy

## Prerequisites

. Have https://www.virtualbox.org/[Oracle Virtualbox] installed and the install folder added to your PATH environment variable.
. Have the https://github.com/arun-gupta/docker-java/ git repository checked out.
. Have https://msysgit.github.io/ installed on windows
. Have http://asciidoctor.org/ installed

#Install asciidoctor

gem install asciidoctor

## Install Docker Client

[source, text]
----
# Linux / MacOS
curl -L  https://get.docker.com/builds/Darwin/x86_64/docker-latest > /usr/local/bin/docker

#Windows 
Download: 
https://get.docker.com/builds/Windows/x86_64/docker-latest.exe
https://get.docker.com/builds/Windows/i386/docker-latest.exe
And save to c:/Users/<username>/docker/docker.exe
----

## Install Docker-machine

Install the Docker machine client for your environment: https://github.com/docker/machine/releases/[latest releases]

[source, text]
----
# Linux / MacOS
curl -L  https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_darwin-amd64 > /usr/local/bin/docker-machine

# Windows
Download:
https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_windows-amd64.exe
And save to c:/Users/<username>/docker/docker-machine.exe
----

For Windows, make sure to add c:/Users/<username>/docker to your %PATH% variable.

## Create Machine

[source, text]
----
docker-machine create --driver virtualbox --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.5.0/boot2docker.iso mymachine
----

## Expose the Virtual Box ports to other computer in the LAN

VirtualBox will run docker container inside the newly create host called 'mymachine'. We need now to expose the ports used in this lab to the world.

[source, text]
----
#Open Registry Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port5000,tcp,,5000,,5000";
#Open Nexus Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8081,tcp,,8081,,8081";
#Open HTTP Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8082,tcp,,8082,,8082";
----


Check machine IP
[source, text]
----
docker-machine ip
----

Further on refered to as <HOST_IP>

## Add extra args to docker host to allow insecure registry for external access via http:
You can either insert your <HOST_IP> or the complete subnet e.g. 192.168.99.100 maps to 192.168.99.0/24

[source, text]
----
docker-machine ssh

$ # add EXTRA_ARGS="--insecure-registry <YOUR INSECURE HOST>" 
$ # to /var/lib/boot2docker/profile
$ sudo /etc/init.d/docker restart
----


## Run local-registry

Instructors should run a local registry to make all images locally available to attendees

[source, text]
----
docker run -d --name="docker-registry" -p 5000:5000 -v /registry:/tmp/registry-dev registry:2.0
----

##Convert the Attendees instructions to HTML.

This instructions will be placed inside the Lab HTTPD Server during the image build

[source, text]
----
asciidoctor ../attendees/readme.adoc -o lab-httpd-server/index.html
----

## Build the Lab HTTPD Server image

Make sure to change to the cloned repository/instructor first.

[source, text]
----
docker build -t lab-httpd-server:latest lab-httpd-server/.
----

## Run Http server with downloadables

Run the Apache HTTPD server for attendees to download boot2docker iso image and Virtuabox binaries.

[source, text]
----
docker run -d --name="lab-httpd-server" -p 8082:80 lab-httpd-server
----

If you run into errors on Windows (eg, no such file or exec format error, check the line ending in the run-apache.sh).

Check if the server is running: http://localhost:8082/

NOTE: Make sure to check your firewall settings. Attendees should be able to access this machine with your local IP.

## Run Nexus On the instructor machine

Default credentials are: admin / admin123

Use a data volume container. Since data volumes are persistent until no containers use them, a container can created specifically for this purpose. 

[source, text]
----
docker run -d --name nexus-data sonatype/nexus:oss echo "data-only container for Nexus"
docker run -d -p 8081:8081 --name nexus --volumes-from nexus-data sonatype/nexus:oss
----

Test if nexus is running:

[source, text]
----
 curl http://localhost:8081/service/local/status
----

Access the nexus console [http://localhost:8081/].