# Docker for Java Developers

This folder contains instructions to setup an Instructor environment.

Instructor needs:

. A docker registry server
. A Boot2docker served by a local HTTP Server
. A Nexus Proxy

## Install Docker Client

[source, text]
----
# Linux / MacOS
curl -L  https://get.docker.com/builds/Darwin/x86_64/docker-latest > /usr/local/bin/docker

#Windows 
Download: 
http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.6.0.exe 
And save to c:/Users/<username>/docker/docker-machine.exe
----

## Install Docker-machine

Install the Docker machine client for your environment: a https://github.com/docker/machine/releases/[latest releases]

[source, text]
----
# Linux / MacOS
curl -L  https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_darwin-amd64 > /usr/local/bin/docker-machine

# Windows
Download:
https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_windows-amd64.exe
And save to c:/Users/<username>/docker/docker-machine.exe
----

For Windows, make sure to add c:/Users/<username>/docker to your %PATH% variable.

## Create Machine

[source, text]
----
docker-machine create --driver virtualbox --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.5.0/boot2docker.iso mymachine
----

## Expose the Virtual Box ports to other computer in the LAN

VirtualBox will run docker container inside the newly create host called 'mymachine'. We need now to expose the ports used in this lab to the world.

[source, text]
----
#Open Registry Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port5000,tcp,,5000,,5000";
#Open Nexus Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8081,tcp,,8081,,8081";
#Open HTTP Server port
VBoxManage controlvm "mymachine" natpf1 "tcp-port8082,tcp,,8082,,8082";
----
## Add extra args to docker host to allow insecure registry for external access via http:

[source, text]
----
docker-machine ssh

$ # add EXTRA_ARGS="--insecure-registry <YOUR INSECURE HOST>" 
$ # to /var/lib/boot2docker/profile
$ sudo /etc/init.d/docker restart
----

Check machine IP
[source, text]
----
docker-machine ip
----

Further on refered to as <HOST_IP>

## Run local-registry

Instructors should run a local registry to make all images locally available to attendees

[source, text]
----
docker run -dp --name="docker-registry" 5000:5000 registry:2.0
----


## Build the Lab HTTPD Server image

[source, text]
----
docker build -t lab-httpd-server:latest lab-httpd-server/.
----

## Run Http server with downloadables

Run the Apache HTTPD server for attendees to download boot2docker iso image and Virtuabox binaries.

[source, text]
----
docker run -d --name="lab-httpd-server" -p 8082:80 lab-httpd-server
----

## Run Nexus On the instructor machine

Default credentials are: admin / admin123

Map the local path <USER_HOME_DIR>/nexus_work to the nexus work directory of the container.
Attention, this is different for boot2docker based Docker hosts.

[source, text]
----
# On Windows Machines
docker run -d -p 8081:8081 -v /c/Users/<username>/nexus_work:/sonatype-work --name nexus sonatype/nexus:oss

# On Linux/MaxOS
docker run -d -p 8081:8081 -v /Users/<username>/nexus_work:/sonatype-work --name nexus sonatype/nexus:oss
----

Test if nexus is running:

[source, text]
----
 curl http://localhost:8081/service/local/status
----

