## Setup Environments

This section describes what, how, and where to install the software needed for this lab. This lab is designed for a BYOL (Brying Your Own Laptop) style hands-on-lab.

### Hardware

. Operating System: Mac OS X (10.8 or later), Windows 7 (SP1), Fedora (21 or later)
. Memory: At least 4 GB+, preferred 8 GB

### Software

. Java: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8u45]
. Web Browser
.. https://www.google.com/chrome/browser/desktop/[Chrome]
.. link:http://www.getfirefox.com[Firefox]

### Git Client

Install Git Client as explained at: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

### Maven

. Download Apache Maven from https://maven.apache.org/download.cgi.
. Unzip to a directory of your choice and add it to the `PATH`.

### VirtualBox

Docker currently runs natively on Linux. It can be configured to run in a virtual machine on Mac or Windows. This is why Virtualbox is a requirement for Mac or Windows.

Downloads are available from https://www.virtualbox.org/.

Virtual Box 5.0.0 does not allow Kubernetes cluster to be started: https://github.com/kubernetes/kubernetes/issues/12614. Make sure to download VirtualBox 4.3.30[https://www.virtualbox.org/wiki/Download_Old_Builds_4_3].

[WARNING]
====
Linux Users

. Have your kernel updated
. Users should have the GNU compiler, build and header files for your current Linux kernel
. Create a `/usr/src/linux` link to the current kernel source
====

### Vagrant

Download Vagrant from https://www.vagrantup.com/downloads.html and install.

### Docker Machine

Docker Machine makes it really easy to create Docker hosts on your computer, on cloud providers and inside your own data center. It creates servers, installs Docker on them, then configures the Docker client to talk to them.

[source, text]
----
# Mac
curl -L https://github.com/docker/machine/releases/download/v0.4.0/docker-machine_darwin-amd64 > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

# Linux
curl -L  https://github.com/docker/machine/releases/download/v0.4.0/docker-machine_linux-amd64 > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

#Windows
curl https://github.com/docker/machine/releases/download/v0.4.0/docker-machine.exe
----

### Create Lab Docker Host

. Create Docker Host to be used in the lab:
+
[source, text]
----
docker-machine create --driver=virtualbox lab
eval "$(docker-machine env lab)"
----
+
Use the following command on Windows:
+
[source, text]
----
(docker-machine env lab --shell cmd
----
+
And then execute all the `set` commands.
+
. To make it easier to start/stop the containers, an entry is added into the host mapping table of your operating system. Find out the IP address of your machine:
+
[source, text]
----
docker-machine ip lab
----
+
This will provide the IP address associated with the Docker Machine created earlier.
+
. Edit `/etc/hosts` (Mac OS or Linux) or `C:\Windows\System32\drivers\etc\hosts` (Windows) and add:
+
[source, text]
----
<IP ADDRESS>  dockerhost
----

### Docker Client

Docker Client is used to communicate with Docker Host.

[source, text]
----
# Mac
curl -L https://get.docker.com/builds/Darwin/x86_64/docker-latest > /usr/local/bin/docker
chmod +x /usr/local/bin/docker

# Linux
curl -L https://get.docker.com/builds/Linux/x86_64/docker-latest > docker-latest-linux
chmod +x /usr/local/bin/docker

# Windows
curl -L http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.7.0.exe -o docker.exe
----

### Kubernetes

. Download Kubernetes (1.0.1) from https://github.com/kubernetes/kubernetes/releases/download/v1.0.1/kubernetes.tar.gz.
. Extract the archive and install it by:

[source, text]
----
export KUBERNETES_PROVIDER=vagrant
cd kubernetes
./cluster/kube-up.sh
----

NOTE: Kubernetes 1.0.1 is the only version verified to work with Virtual Box. More details at: https://github.com/kubernetes/kubernetes/issues/12614

### WildFly

. Download WildFly 9.0 from http://download.jboss.org/wildfly/9.0.0.Final/wildfly-9.0.0.Final.zip.
. Install it by extracting the archive.

### JBoss Developer Studio 9 - Beta 2

To install JBoss Developer Studio stand-alone, complete the following steps:

. Download http://tools.jboss.org/downloads/devstudio/mars/9.0.0.Beta2.html[9.0.0 Beta 2] or
https://devstudio.redhat.com/9.0/snapshots/builds/devstudio.product_master/latest/installer/[Latest Nightly].
. Start the installer as:
+
[source, text]
----
java -jar <JAR FILE NAME>
----
+
Follow the on-screen instructions to complete the installation process.

### Pull Docker images

IMPORTANT: These commands need to be issued from the shell or command prompt where `docker-machine env lab` and associated commands were issued.

[source, text]
----
docker pull jboss/wildfly
docker pull arungupta/wildfly-management
docker pull arungupta/javaee7-hol
docker pull mysql
docker pull swarm
docker pull arungupta/wildfly-mysql-javaee7
----
