## Setup Environments

This section describes the relevant steps for both attendees and instructors to setup the environments. Please follow the parts, that are appropriate for you.

### Instructor

The instructor setup is designed to make the lab most reliable even with bad Internet connections. Most if not all of the software can be directly downloaded from the instructor's machine. The machine is setup as _Docker Host_ and also runs a _Docker Registry_.

Execute link:../instructor/readme.adoc[instructor setup instructions] at least a day before the lab.

### Attendees (From Instructor Machine)

This lab is designed for a BYOL (Brying Your Own Laptop) style hands-on-lab. This folder contains instructions to setup an attendee environment. We did our best to support a wide range of client configurations but only did test on machines as stated in the hardware section.

Please note, that it is only intended to setup the environment for this lab. The lab itself is at https://github.com/javaee-samples/docker-java/.

Here are the requirements for attendees to complete this lab:

#### Hardware

. CPU
.. Mac: X64 (i5 or superior)
.. Linux / Windows: x64 (i5 and comparable)

. Memory
.. At least 4GB, preferred 8 GB

#### Software

. Operating System
.. Mac OS X (10.8 or later), Windows 7 (SP1), Fedora (21 or later)
. Java: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8u45]
. Webbrowser
.. https://www.google.com/chrome/browser/desktop/[Chrome]
.. link:http://www.getfirefox.com[Firefox]


#### A Word About Licenses
This tutorial only uses software which is open source or at least free to use in development and/or education. Please refer to the individual products/tools used in this tutorial.

. Docker is Apache License Version 2.0, see it here: https://github.com/docker/docker/blob/master/LICENSE
. VirtualBox base packages (everything but the extension pack) is released under the GNU General Public License V2, see it here: https://www.virtualbox.org/wiki/GPL
. Msysgit is a fork of Git under the GNU General Public License version 2.0, see it here: http://opensource.org/licenses/GPL-2.0

[[Configure_Instructor_Host]]
#### Configure Instructor Host

All downloads and relevant infrastructure is setup on instructor's machine. Configure the IP address of instructor's machine into the host mapping table of your operating system.

Edit the `/etc/resolv.conf` (Mac OS / Linux) - TODO - Configure Windows

[source, text]
----
nameserver  <INSTRUCTOR UP>
----

#### Git Client

Install Git Client as explained at: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

Windows client is available at http://classroom.example.com:8082/downloads/.

#### Maven

. Download Apache Maven from http://classroom.example.com:8082/downloads/apache-maven-3.3.3-bin.zip
. Unzip to a folder of your choice and add the folder to your PATH environment variable. For example, do the following on Windows:

  set PATH=%PATH%;c:/apache-maven-3.3.3

#### VirtualBox

Docker currently runs natively on Linux, but you can use VirtualBox to run Docker in a virtual machine on your box, and get the best of both worlds. This is why Virtualbox is a requirement to have on your machine. Get the latest downloads from the instructur machine:

Downloads are available at http://classroom.example.com:8082/downloads/ or directly from the https://www.virtualbox.org/[Oracle Virtualbox] website.

Installation should complete without any error.

[WARNING]
====
Linux Users

. Have your kernel updated
. Users should have the GNU compiler, build and header files for your current Linux kernel
. Create a `/usr/src/linux` link to the current kernel source
====

#### Vagrant

. Download Vagrant from http://classroom.example.com:8082/downloads/ for your specific operating system.
. Install it by clicking on the archive.


#### Docker Machine

Download your binary from http://classroom.example.com:8082/downloads/

[source, text]
----
# MacOS
curl -L  http://classroom.example.com:8082/downloads/docker-machine_darwin-amd64 > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

# Linux
curl -L  http://classroom.example.com:8082/downloads/docker-machine_linux-amd64 > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

#Windows
curl http://classroom.example.com:8082/downloads/docker-machine_windows-amd64.exe
----

On Windows copy the script into `C:\docker` directory and rename to: `docker-machine.exe`. Add `C:\docker` to your `PATH` variable.

[source, text]
----
# Windows Only
set PATH=%PATH%;c:\docker
----

#### Docker Client

Download your binary from http://classroom.example.com:8082/downloads/

[source, text]
----
# MacOS
curl -L  http://classroom.example.com:8082/downloads/docker-latest-mac > /usr/local/bin/docker
chmod +x /usr/local/bin/docker

# Linux (other distros)
curl -L  http://classroom.example.com:8082/downloads/docker-latest-linux > /usr/local/bin/docker
chmod +x /usr/local/bin/docker

#Windows
curl http://classroom.example.com:8082/docker-1.6.0.exe
----

On Windows rename the file to `C:\docker\docker.exe`.

#### Create Lab Docker Host

. Create the Docker Host to be used in the lab:
+
[source, text]
----
docker-machine create --driver=virtualbox --engine-opt dns=<INSTRUCTOR UP> --virtualbox-boot2docker-url=http://classroom.example.com:8082/downloads/boot2docker.iso --engine-insecure-registry=classroom.example.com:5000 lab
eval "$(docker-machine env lab)"
----
+
Substitute `<INSTRUCTOR_IP>` with the IP address of the instructor's machine.
+
This will allow to download all Docker images from instructor's machine, using both IP address and hostname.
+
. Add a host entry for this Docker Host running on your machine. To make it easier to access the containers, we add an entry into the host mapping table of your operating system. Find out the IP address of your machine:
+
[source, text]
----
docker-machine ip lab
----
+
. Edit the `/etc/hosts` (Mac OS) or `C:\Windows\System32\drivers\etc\hosts` (Windows) and add:
+
[source, text]
----
<OUTPUT OF DOCKER MACHINE COMMAND>  dockerhost
----

#### Kubernetes

. Download Kubernetes (0.18.1) from http://classroom.example.com:8082/downloads/kubernetes.tar.gz
. Install it by clicking on the archive.

#### WildFly

. Download WildFly 8.2 from http://classroom.example.com:8082/downloads/wildfly-8.2.0.Final.zip
. Install it by clicking on the archive.

#### JBoss Developer Studio 9 - Beta 2

To install JBoss Developer Studio stand-alone, complete the following steps:

. Download http://classroom.example.com:8082/downloads/jboss-devstudio-9.0.0.Beta2-v20150609-1026-B3346-installer-standalone.jar
. Start the installer as:
+
[source, text]
----
java -jar jboss-devstudio-9.0.0.Beta2-v20150609-1026-B3346-installer-standalone.jar
----
+
Follow the on-screen instructions to complete the installation process.


### Attendees (From Internet)

. Chrome or Firefox
. http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8 u45]
. https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[Git client]
. https://maven.apache.org/download.cgi[Maven 3.3.3]
. Latest https://www.virtualbox.org/[Virtual Box]
. https://www.vagrantup.com/downloads.html[Vagrant]
. Docker
.. https://docs.docker.com/machine/#installation[Docker Machine]
.. Docker Client
... Mac: `curl https://get.docker.com/builds/Darwin/x86_64/docker-latest > /usr/local/bin/docker`
... Windows: http://test.docker.com.s3.amazonaws.com/builds/Windows/x86_64/docker-1.6.0.exe
... Linux: `apt-get install docker.io`
. https://github.com/GoogleCloudPlatform/kubernetes/releases/download/v0.18.1/kubernetes.tar.gz[Kubernetes 0.18.1]
. JBoss
.. http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.zip[WildFly 8.2]
.. https://devstudio.redhat.com/9.0/snapshots/builds/devstudio.product_master/latest/installer/[JBoss Developer Studio 9 Nightly]
