== Troubleshooting

=== Network Timed Out

Depending upon the network speed and restrictions, you may not be able to download Docker images from Docker Hub. The error message may look like:

[source, text]
----
$ docker pull arungupta/wildfly-mysql-javaee7
Using default tag: latest
Pulling repository docker.io/arungupta/wildfly-mysql-javaee7
Network timed out while trying to connect to https://index.docker.io/v1/repositories/arungupta/wildfly-mysql-javaee7/images. You may want to check your internet connection or if you are behind a proxy.
----

This section provide a couple of alternatives to solve this.

==== Restart Docker Machine

It seems like Docker Machine gets into a strange state and restarting it fixes that.

[source, text]
----
docker-machine restart <MACHINE_NAME>
eval $(docker-machine env <MACHINE_NAME>)
----

==== Loading Images Offline

Images can be downloaded from a previously saved `.tar` file. All images required for this workshop can be downloaded from:

https://drive.google.com/folderview?id=0B8g4lYJ4uB37RkdqbFpPZU5ZS2s&usp=sharing

Load the tar file:

[source, text]
----
docker load -i <path to image tar file>
----

For example:

[source, text]
----
docker load -i arungupta-javaee7-hol.tar
----

Now `docker images` should show the image.

=== Cannot create Docker Machine on Windows

Are you not able to create Docker Machine on Windows?

Try starting a `cmd` with Administrator privileges and then give the command again.
