## Setup Environments

This section describes what, how, and where to install the software needed for this lab. This lab is designed for a BYOL (Brying Your Own Laptop) style hands-on-lab.

### Hardware

. Operating System: Mac OS X (10.8+), Windows 7+, Ubuntu 12+, CentOS 7+, Fedora 21+
. Memory: At least 4 GB+, preferred 8 GB

### Docker

#### Docker Toolbox or Packages

Docker runs natively on Linux. Because the Docker daemon uses Linux-specific kernel features, you can’t run Docker natively in OS X or Windows. Instead, you must use `docker-machine` to create and attach to a virtual machine (VM). This machine is a Linux VM that hosts Docker for you on your Mac or Windows. This can be easily installed using https://www.docker.com/docker-toolbox[Docker Toolbox].

Follow the instructions to install Docker:

. https://github.com/docker/toolbox/releases/download/v1.9.0/DockerToolbox-1.9.0.pkg[Docker Tool Box 1.9.0 for Mac]
. https://github.com/docker/toolbox/releases/download/v1.9.0/DockerToolbox-1.9.0.exe[Docker Toolbox 1.9.0 for Windows]
. http://docs.docker.com/engine/installation/ubuntulinux/[Docker on Ubuntu]
. http://docs.docker.com/engine/installation/centos/[Docker on Centos]
. http://docs.docker.com/engine/installation/fedora/[Docker on Fedora]

Complete set of operating systems are listed at http://docs.docker.com/engine/installation/[Install Docker Engine].

#### Pull Docker images

IMPORTANT: For Mac and Windows, these commands need to be issued from the Docker shell or command prompt where `eval $(docker-machine env default)` command was issued.

[source, text]
----
docker pull jboss/wildfly
docker pull arungupta/wildfly-management
docker pull arungupta/javaee7-hol
docker pull mysql
docker pull swarm
docker pull arungupta/wildfly-mysql-javaee7
----

#### Create Docker Swarm Cluster

Create Docker Swarm cluster as:

[source, text]
----
docker run swarm create
----

This will generate a token. Use this token to create a Swarm Master.

[source, text]
----
docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://<token> swarm-master
----

Detailed explanation for this is available in <<Docker_Swarm>>.

#### Create Docker Host Mapping

. To make it easier to start/stop the containers, an entry is added into the host mapping table of your operating system. Find out the IP address of your machine:
+
[source, text]
----
docker-machine ip default
----
+
This will provide the IP address associated with the Docker Machine created earlier.
+
. Edit `/etc/hosts` (Mac OS or Linux) or `C:\Windows\System32\drivers\etc\hosts` (Windows) and add:
+
[source, text]
----
<IP ADDRESS>  dockerhost
----

#### Optional Software

The following software needs to be downloaded if you want to build/deploy a Java EE application.

##### Java Development Kit

. Java: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8u65]

##### Maven

. Download Apache Maven from https://maven.apache.org/download.cgi.
. Unzip to a directory of your choice and add it to the `PATH`.

##### WildFly

. Download WildFly 9.0 from http://download.jboss.org/wildfly/9.0.0.Final/wildfly-9.0.0.Final.zip.
. Install it by extracting the archive.

##### JBoss Developer Studio 9.0

To install JBoss Developer Studio stand-alone, complete the following steps:

. Download http://tools.jboss.org/downloads/devstudio/mars/9.0.0.GA.html[9.0.0].
. Start the installer as:
+
[source, text]
----
java -jar <JAR FILE NAME>
----
+
Follow the on-screen instructions to complete the installation process.

[[Kubernetes_Setup]]
### Kubernetes

. Download Vagrant from https://www.vagrantup.com/downloads.html and install.
+
Kubernetes requires Vagrant >= 1.6.2. So if you have an older version then make sure you install the latest one.
+
. Download Kubernetes (1.0.1) from https://github.com/kubernetes/kubernetes/releases/download/v1.0.1/kubernetes.tar.gz.
. Extract the archive and install it by:

[source, text]
----
export KUBERNETES_PROVIDER=vagrant
cd kubernetes
./cluster/kube-up.sh
----

NOTE: Kubernetes 1.0.1 is the only version verified to work with Virtual Box. More details at: https://github.com/kubernetes/kubernetes/issues/12614


