== Kubernetes and Fabric8
Fabric8 is a set of tools and services geared toward middleware and application developers that make it easy to develop microervices using Docker and Kubernetes.

=== Fabic 8 Console

The Fabric8 console is rich with visual diagrams showing what you've got deployed, where it's deployed, how many, and so on. You can also make changes to your kubernetes cluster (deploy apps, edit replica sizes, delete services, etc) from a single dashboard. Screen shots and demos to come.


=== Inject k8s resources using @Inject in Java EE client
Fabric8 has lots of java [libraries](http://fabric8.io/guide/javaLibraries.html) for making working with kubernetes and kubernetes resources easier. For example, there is a [kubernetes Java client](https://github.com/fabric8io/kubernetes-client) with a fluent DSL for interacting with the Kube API. More examples to come.

=== Maven plugin to generate JSON for your WAR file and deploy it in k8s
Java developers are used to Maven and other tools in the Java ecosystem. Fabric8's maven plugins aim to bridge the gap between app development and the kubernetes cluster engine. With these plugins you can create docker images and control how they're created using Maven properties and plugin configurations. You can also generate the kubenetes JSON files, inject environment variables, and also apply the JSON directly to Kube.

=== Built in CI/CD with workflow and promotion
Java developers eventually want to deploy their application. Fabric8 brings a set of curated, yet pluggable, services like Git, Jenkins, Nexus, Gerrit and integrates them together with an issue tracker, chat room, and flexible per-project configurations which allow you to set up CI/CD with proper gates and promotion practices with a single click or with a single yml file.

=== Out of the box tooling for your Apache Camel apps
Apache Camel is a very powerful integration library and can be used along with Fabric8 and Kubernetes to provide an iPaaS. The tooling included in Fabric8 gives a UI based access to visualizations, debugging, tracing, metrics and indicators, etc.

=== API management for your APIs
Accessing your services can become complicated if you consider token provisioning, authZ/authN, metering, chargeback, etc,etc. Fabric8 has built in API management for your APIs.

=== Logging/Metrics for your apps built in
Fabric8 leverages InfluxDB/Grafana and Elasticsearch/Kibana for in-container metrics and logging that is valuable for any insight into what your apps or middleware are doing

