## Setup Environments

This section describes the software needed for this workshop. This workshop is designed for a BYOL (Brying Your Own Laptop) style hands-on-lab.

### Hardware

. Operating System: Mac OS X (10.8+), Windows 7+, Ubuntu 12+, CentOS 7+, Fedora 21+
. Memory: At least 4 GB+, preferred 8 GB

### Docker

#### Docker Toolbox or Packages

Docker runs natively on Linux. Because the Docker daemon uses Linux-specific kernel features, you can’t run Docker natively in OS X or Windows. Instead, you must use `docker-machine` to create and attach to a virtual machine (VM). This machine is a Linux VM that hosts Docker for you on your Mac or Windows. This can be easily installed using https://www.docker.com/docker-toolbox[Docker Toolbox].

Follow the instructions to install Docker:

. https://github.com/docker/toolbox/releases/download/v1.9.0/DockerToolbox-1.9.0.pkg[Docker Tool Box 1.9.0 for Mac]
. https://github.com/docker/toolbox/releases/download/v1.9.0/DockerToolbox-1.9.0.exe[Docker Toolbox 1.9.0 for Windows]
. http://docs.docker.com/engine/installation/ubuntulinux/[Docker on Ubuntu]
. http://docs.docker.com/engine/installation/centos/[Docker on Centos]
. http://docs.docker.com/engine/installation/fedora/[Docker on Fedora]

Complete set of operating systems are listed at http://docs.docker.com/engine/installation/[Install Docker Engine].

#### Checkout `docker-java` workspace

```console
git clone https://github.com/javaee-samples/docker-java
```

#### Pull Docker images

IMPORTANT: For Mac and Windows, this commands need to be issued from the Docker shell or Command Prompt where `eval $(docker-machine env default)` command was issued. This command need to be issued in the `attendees` directory of `docker-java` workspace.

```console
docker-compose -f docker-compose-pull-images.yml pull
```

#### Create Docker Host Mapping

. To make it easier to start/stop the containers, an entry is added into the host mapping table of your operating system. Find out the IP address of your machine:
+
```console
docker-machine ip default
```
+
This will provide the IP address associated with the Docker Machine created earlier.
+
. Edit `/etc/hosts` (Mac OS or Linux) or `C:\Windows\System32\drivers\etc\hosts` (Windows) and add:
+
[source, text]
----
<IP ADDRESS>  dockerhost
----

#### Optional Software

The following software needs to be downloaded if you want to build/deploy a Java EE application.

##### Java Development Kit

. Java: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8u65]

##### Maven

. Download Apache Maven from https://maven.apache.org/download.cgi.
. Unzip to a directory of your choice and add it to the `PATH`.

##### WildFly

. Download WildFly 9.0 from http://download.jboss.org/wildfly/9.0.0.Final/wildfly-9.0.0.Final.zip.
. Install it by extracting the archive.

##### JBoss Developer Studio 9.0

To install JBoss Developer Studio stand-alone, complete the following steps:

. Download http://tools.jboss.org/downloads/devstudio/mars/9.0.0.GA.html[9.0.0].
. Start the installer as:
+
```console
java -jar <JAR FILE NAME>
```
+
Follow the on-screen instructions to complete the installation process.

[[Kubernetes_Setup]]
### Kubernetes

. Download Vagrant from https://www.vagrantup.com/downloads.html and install.
+
Kubernetes requires Vagrant >= 1.6.2. So if you have an older version then make sure you install the latest one.
+
. If you've not installed Docker Toolbox, then you need to additionally download Virtual Box 5.0.8 from https://www.virtualbox.org/wiki/Downloads.
. Download Kubernetes (1.1.2) from https://github.com/kubernetes/kubernetes/releases/download/v1.1.3/kubernetes.tar.gz.
. On Windows, Python interpreter needs to be installed and included in the `%PATH%`. Download from https://www.python.org/downloads/windows/ and setup `%PATH%` in Control Panel.
. Extract the archive and install it:
+
```console
export KUBERNETES_PROVIDER=vagrant
cd kubernetes
./cluster/kube-up.sh
```
+
NOTE: Vagrant provider should be included in the path. For example, for VirtualBox, `vboxmanage` command should work from the shell or command prompt where `./cluster/kube-up.sh` script is invoked.
+
If more than one Vagrant provider (such as VirtualBox and Parallels) are installed, Kubernetes will usually pick the appropriate one. You can override by setting the VAGRANT_DEFAULT_PROVIDER environment variable:
+
```console
export VAGRANT_DEFAULT_PROVIDER=virtualbox
export KUBERNETES_PROVIDER=vagrant
./cluster/kube-up.sh
```
+
NOTE: This will take a few minutes, so be patience! Vagrant will provision each machine in the cluster with all the necessary components to run Kubernetes.
+
+
It shows the output as:
+
[source, text]
----
kubernetes > ./cluster/kube-up.sh 
... Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion-1' up with 'virtualbox' provider...
==> master: Importing base box 'kube-fedora21'...
==> master: Matching MAC address for NAT networking...
==> master: Setting the name of the VM: kubernetes_master_1450804087843_75902

. . .

... calling validate-cluster
Found 1 node(s).
NAME         LABELS                              STATUS    AGE
10.245.1.3   kubernetes.io/hostname=10.245.1.3   Ready     5s
Validate output:
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   nil
scheduler            Healthy   ok                   nil
etcd-0               Healthy   {"health": "true"}   nil
etcd-1               Healthy   {"health": "true"}   nil
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://10.245.1.2
Heapster is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-ui
Grafana is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
----
+
Note down the address for Kubernetes master, `https://10.245.1.2` in this case.
