== Troubleshooting

=== Network Timed Out

Depending upon the network speed and restrictions, you may not be able to download Docker images from Docker Hub. The error message may look like:

[source, text]
----
$ docker pull arungupta/wildfly-mysql-javaee7
Using default tag: latest
Pulling repository docker.io/arungupta/wildfly-mysql-javaee7
Network timed out while trying to connect to https://index.docker.io/v1/repositories/arungupta/wildfly-mysql-javaee7/images. You may want to check your internet connection or if you are behind a proxy.
----

This section provide a couple of alternatives to solve this.

==== Restart Docker Machine

It seems like Docker Machine gets into a strange state and restarting it fixes that.

[source, text]
----
docker-machine restart <MACHINE_NAME>
eval $(docker-machine env <MACHINE_NAME>)
----

==== Loading Images Offline

Images can be downloaded from a previously saved `.tar` file. All images required for this workshop can be downloaded from:

https://drive.google.com/folderview?id=0B8g4lYJ4uB37RkdqbFpPZU5ZS2s&usp=sharing

Load the tar file:

[source, text]
----
docker load -i <path to image tar file>
----

For example:

[source, text]
----
docker load -i arungupta-javaee7-hol.tar
----

Now `docker images` should show the image.

=== Cannot create Docker Machine on Windows

Are you not able to create Docker Machine on Windows?

Try starting a `cmd` with Administrator privileges and then give the command again.

=== No route to host

Accessing the WildFly and MySQL sample in Kubernetes gives 404 when you give the command `curl http://10.246.1.23:8080/employees/resources/employees/`.

This may be resolved by stopping the node and restarting the cluster again:

[source, text]
----
vagrant halt minion-1
./cluster/kube-up.sh
----

These commands need to be given in the '`kubernetes`' directory.

=== Docker machine creation fails with an error about dial tcp: i/o timeout

If you get the following error when creating a docker machine

[source, text]
----
Error creating machine: Error in driver during machine creation: Get https://api.github.com/repos/boot2docker/boot2docker/releases: dial tcp: i/o timeout
----

Then you need to go to the boot2docker releases page on

https://github.com/boot2docker/boot2docker/releases

And download the latest .iso

After that you can move that iso to the docker cache directory. This is located in `~/.docker/machine/cache` on Mac & Linux and `/Users/yourUserName/.docker/machine/cache` on Windows.

Issue: https://github.com/docker/machine/issues/2186 is raised so that the docker-machine team can hopefully find a way around this.
