= Docker for Java Developers - Attendee Setup
:toc:
:toc-placement!:

This folder contains instructions to setup an attendee environment. Please note, that it is only intended to setup the environment for this lab. The lab itself is in the link:https://github.com/arun-gupta/docker-java/blob/master/readme.adoc[main readme]. Continue with it after you finished this setup.
You'll learn about all the software you installed here during the lab. For now just go through this document and let'#'s get ready as fast as possible for the lab.

Your instructor will have a a machine setup with all the relevant downloads and needed infrastructures. The IP will change depending on the network used. In this guide, it's refered to as <INSTRUCTOR_IP> make sure to replace this with the actuall IP address you get from your instructor.

toc::[]

## Prerequisites
This lab can be executed on a netbook with x86 architecture. For it to
be fun, you should have a decent hardware available. Beside the operating system of choice, there's only a couple of other thing you should have installed already:

### Hardware

. CPU
.. Mac: X64 (i5 or superior)
.. Linux / Windows: x86 (Intel Pentium) or x64 (i5 and comparable)

. Memory
.. At least 4 to 8 GB

### Software

. Operating System
.. Mac OS X (10.8 or later), Windows 7 (SP1), Fedora (21 or later)
. Java
.. http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8u45]
. Webbrowser
.. https://www.google.com/chrome/browser/desktop/[Chrome]
.. link:http://www.getfirefox.com[Firefox]


## A word about licenses
This tutorial only uses software which is open source or at least free to use in development and/or education.
Please refer to the individual products/tools used in this tutorial.
. Docker is Apache License Version 2.0, see it here: https://github.com/docker/docker/blob/master/LICENSE
. VirtualBox base packages (everything but the extension pack) is released under the GNU General Public License V2, see it here: https://www.virtualbox.org/wiki/GPL
. Msysgit is a fork of Git under the GNU General Public License version 2.0, see it here: http://opensource.org/licenses/GPL-2.0

## Install VirtualBox

Docker currently runs natively on Linux, but you can use VirtualBox to run Docker in a virtual machine on your box, and get the best of both worlds. This is why Virtualbox is a requirement to have on your machine. Get the latest downloads from the instructur machine:

Downloads are available at http://<INSTRUCTOR_IP:8082>/downloads/

or directly from the https://www.virtualbox.org/[Oracle Virtualbox] website.

NOTE: Installation should complete without any error!

CAUTION: Linux Users
. Have your kernel updated
. Users should have the GNU compiler, build and header files for your current Linux kernel
. Create a /usr/src/linux link to the current kernel source

CAUTION: Windows Users
. Have https://msysgit.github.io/ installed


## Install Docker Machine

Download your binary from http://<INSTRUCTOR_IP:8082>/downloads/

[source, text]
----
# MacOS
curl -L  http://<INSTRUCTOR_IP>:8082/downloads/docker-machine_darwin-amd64 > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

# Linux
curl -L  http://<INSTRUCTOR_IP>:8082/downloads/docker-machine_linux-amd64 > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

#Windows
curl http://<INSTRUCTOR_IP>:8082/downloads/docker-machine_windows-amd64.exe
----

On Windows copy the script into `C:\docker` directory and rename to: `docker-machine.exe`. Add `C:\docker` to your `PATH` variable.

[source, text]
----
# Windows Only
set PATH=%PATH%;c:\docker
----

## Install Docker Client

Download your binary from http://<INSTRUCTOR_IP>:8082/downloads/

[source, text]
----
# MacOS / Linux (other distros)
curl -L  http://<INSTRUCTOR_IP>:8082/`uname -s`/x86_64/docker-latest > /usr/local/bin/docker
chmod +x /usr/local/bin/docker

#Windows
curl http://<INSTRUCTOR_IP>:8082/docker-1.6.0.exe
----

On Windows put into and rename to `C:\docker\docker.exe`.

## Create Lab Docker Host

. Create the Docker Host to be used in the lab:
+
[source, text]
----
docker-machine create --driver virtualbox --virtualbox-boot2docker-url http://<INSTRUCTOR_IP>:8082/downloads/boot2docker.iso lab
----
+
. Setup the host to connect to insecure registries:
+
[source, text]
----
#TODO This boot2docker instruction is being overwritten. Docker-machine will profine flags for this configuration: https://github.com/docker/machine/pull/1040
TODO To avoid it to be overwritten the parameter should be included manually. This issue should be fixed on next docker-machine release.
docker-machine ssh lab "echo $'EXTRA_ARGS=\"--insecure-registry <INSTRUCTOR_IP>:5000\"' | sudo tee -a /var/lib/boot2docker/profile && sudo /etc/init.d/docker restart"
eval "$(docker-machine env lab)"
----

## Install Maven
Download apache-maven-3.3.3-bin.zip from the instructor PC.
[source, text]
----
curl http://<INSTRUCTOR_IP>:8082/downloads/apache-maven-3.3.3-bin.zip
----

unzip to a folder of your choice and add the folder to your PATH environment variable.

[source, text]
----
set PATH=%PATH%;c:/apache-maven-3.3.3
----

## Prepare Maven settings.xml file

Download the lab-settings.xml file from http://<INSTRUCTOR_IP>:8082/downloads/lab-settings.xml

Edit the model file and replace the <INSTRUCTOR_IP>.


## Setup JBoss Developer Studio

To install JBoss Developer Studio stand-alone, complete the following steps:
. Download http://<INSTRUCTOR_IP:8082>/downloads/jboss-devstudio-8.1.0.GA-jar_universal.jar
. Start the installer (see below)
. Follow the on-screen instructions to complete the installation process.

[source, text]
----
# Linux / MacOS / windows
cd /download/path/
java -jar jboss-devstudio-8.1.0.GA-jar_universal.jar
----

## Add a host entry for your dockerhost
To make it easiert to access the containers we add an entry into the host mapping table.
First, find out the IP address of your machine:


[source, text]
----
docker-machine ip
----

And edit the /etc/hosts (Mac OS) or C:\Windows\System32\drivers\etc\hosts (Windows)
and add
[source, text]
----
<OUTPUT OF DOCKER MACHINE COMMAND>  dockerhost
----
