= Docker for Java Developers - Attendee Setup
:toc:
:toc-placement!:

This folder contains instructions to setup an attendee environment. Please note, that it is only intended to setup the environment for this lab. The lab itself is in the link:https://github.com/arun-gupta/docker-java/blob/master/readme.adoc[main readme]. Continue with it after you finished this setup.
You'll learn about all the software you installed here during the lab. For now just go through this document and let'#'s get ready as fast as possible for the lab.

toc::[]

## Prerequisites

Here are the requirements for attendees to complete this lab:

### Hardware

. CPU
.. Mac: X64 (i5 or superior)
.. Linux / Windows: x64 (i5 and comparable)

. Memory
.. At least 4 to 8 GB

### Software

. Operating System
.. Mac OS X (10.8 or later), Windows 7 (SP1), Fedora (21 or later)
. Java
.. http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8u45]
. Webbrowser
.. https://www.google.com/chrome/browser/desktop/[Chrome]
.. link:http://www.getfirefox.com[Firefox]


## A Word About Licenses
This tutorial only uses software which is open source or at least free to use in development and/or education. Please refer to the individual products/tools used in this tutorial.

. Docker is Apache License Version 2.0, see it here: https://github.com/docker/docker/blob/master/LICENSE
. VirtualBox base packages (everything but the extension pack) is released under the GNU General Public License V2, see it here: https://www.virtualbox.org/wiki/GPL
. Msysgit is a fork of Git under the GNU General Public License version 2.0, see it here: http://opensource.org/licenses/GPL-2.0

[[Configure_Instructor_Host]]
## Configure Instructor Host

All downloads and relevant infrastructure is setup on instructor's machine. Configure the IP address of instructor's machine into the host mapping table of your operating system.

Edit the `/etc/hosts` (Mac OS) or `C:\Windows\System32\drivers\etc\hosts` (Windows) and add:

[source, text]
----
<INSTRUCTOR_IP>  dockerlab
----

## Install VirtualBox

Docker currently runs natively on Linux, but you can use VirtualBox to run Docker in a virtual machine on your box, and get the best of both worlds. This is why Virtualbox is a requirement to have on your machine. Get the latest downloads from the instructur machine:

Downloads are available at http://dockerlab:8082/downloads/

or directly from the https://www.virtualbox.org/[Oracle Virtualbox] website.

Installation should complete without any error.

[WARNING]
====
Linux Users

. Have your kernel updated
. Users should have the GNU compiler, build and header files for your current Linux kernel
. Create a `/usr/src/linux` link to the current kernel source
====

## Install Git Client

Install Git Client as explained at: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

## Install Docker Machine

Download your binary from http://dockerlab:8082/downloads/

[source, text]
----
# MacOS
curl -L  http://dockerlab:8082/downloads/docker-machine_darwin-amd64 > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

# Linux
curl -L  http://dockerlab:8082/downloads/docker-machine_linux-amd64 > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

#Windows
curl http://dockerlab:8082/downloads/docker-machine_windows-amd64.exe
----

On Windows copy the script into `C:\docker` directory and rename to: `docker-machine.exe`. Add `C:\docker` to your `PATH` variable.

[source, text]
----
# Windows Only
set PATH=%PATH%;c:\docker
----

## Install Docker Client

Download your binary from http://dockerlab:8082/downloads/

[source, text]
----
# MacOS / Linux (other distros)
curl -L  http://dockerlab:8082/`uname -s`/x86_64/docker-latest > /usr/local/bin/docker
chmod +x /usr/local/bin/docker

#Windows
curl http://dockerlab:8082/docker-1.6.0.exe
----

On Windows rename the file to `C:\docker\docker.exe`.

## Create Lab Docker Host

. Create the Docker Host to be used in the lab:
+
[source, text]
----
docker-machine create --driver virtualbox --virtualbox-boot2docker-url http://dockerlab:8082/downloads/boot2docker.iso lab
----
+
. Setup the Docker Host to connect to insecure registries:
+
[source, text]
----
docker-machine ssh lab "echo $'EXTRA_ARGS=\"\$EXTRA_ARGS --insecure-registry <INSTRUCTOR_IP>:5000\"' | sudo tee -a /var/lib/boot2docker/profile && sudo /etc/init.d/docker restart"
eval "$(docker-machine env lab)"
----
+
Substitute `<INSTRUCTOR_IP>` with the IP address of the instructor's machine.
+
This will allow to download all Docker images from instructor's machine.
+
. Add a host entry for this Docker Host running on your machine. To make it easier to access the containers, we add an entry into the host mapping table of your operating system. Find out the IP address of your machine:
+
[source, text]
----
docker-machine ip lab
----
+
. Edit the `/etc/hosts` (Mac OS) or `C:\Windows\System32\drivers\etc\hosts` (Windows) and add:
+
[source, text]
----
<OUTPUT OF DOCKER MACHINE COMMAND>  dockerhost
----

## Install Maven

. Download Apache Maven from http://dockerlab:8082/downloads/apache-maven-3.3.3-bin.zip
. Unzip to a folder of your choice and add the folder to your PATH environment variable. For example, do the following on Windows:

  set PATH=%PATH%;c:/apache-maven-3.3.3

## Setup JBoss Developer Studio

To install JBoss Developer Studio stand-alone, complete the following steps:

. Download http://dockerlab:8082/downloads/jboss-devstudio-8.1.0.GA-jar_universal.jar
. Start the installer as:
+
[source, text]
----
java -jar jboss-devstudio-8.1.0.GA-jar_universal.jar
----
+
Follow the on-screen instructions to complete the installation process.


## Install Vagrant

. Download Vagrant from http://dockerlab:8082/downloads/ for your specific operating system.
. Install it by clicking on the archive.

